FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-devel

RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    wget \
    git \
    build-essential \
    ca-certificates \
    bzip2 \
    zip \
&& rm -rf /var/lib/apt/lists/*
 
# Set up time zone.
ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Asia/Seoul
RUN apt update && apt install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/*

# Ensure pip installs packages in conda's environment, not ~/.local
ENV PIP_CONFIG_FILE=/dev/null

# Create a new user with sudo privileges
ARG USERNAME=user
RUN useradd -m -s /bin/bash $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && usermod -aG sudo $USERNAME

# Switch to the new user
USER $USERNAME
WORKDIR /home/$USERNAME

# Set the default command
CMD ["/bin/bash"]
